$env:DB_USERNAME = "admin"
$env:DB_PASSWORD = "admin123"
$env:SSL_KEYSTORE_PASSWORD = "password"
$env:JWT_SECRET = "myweb-secret-key-min-256-bits-for-hs256-encoding-please-change-in-production"
$env:APP_ENCRYPTION_KEY = "12345678901234567890123456789012"
# Add your real OAuth keys here
$env:GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID_VALUE"
$env:GOOGLE_CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET_VALUE"
$env:FACEBOOK_APP_ID = "YOUR_FACEBOOK_APP_ID_VALUE"
$env:FACEBOOK_APP_SECRET = "YOUR_FACEBOOK_APP_SECRET_VALUE"
$env:GITHUB_CLIENT_ID = "YOUR_GITHUB_CLIENT_ID_VALUE"
$env:GITHUB_CLIENT_SECRET = "YOUR_GITHUB_CLIENT_SECRET_VALUE"
$env:INDEED_CLIENT_ID = "YOUR_INDEED_CLIENT_ID_VALUE"
$env:INDEED_CLIENT_SECRET = "YOUR_INDEED_CLIENT_SECRET_VALUE"



java -jar target/myweb-0.0.1-SNAPSHOT.jar > backend_jar.log 2>&1


