import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

const translations = {
    vi: {
        // Navbar
        nav_products: 'SẢN PHẨM & GIẢI PHÁP',
        nav_about: 'VỀ CHÚNG TÔI',
        nav_contact: 'LIÊN HỆ',
        nav_lab: 'LAB & TOOLS',
        nav_ctf: 'CTF Arena',
        nav_scanner: 'Security Scanner',
        nav_news: 'BLOG & TIN TỨC',
        nav_recruitment: 'TUYỂN DỤNG',
        nav_login: 'Đăng nhập',
        nav_dashboard: 'Bảng điều khiển',
        nav_logout: 'Đăng xuất',
        nav_intro: 'Giới thiệu',
        nav_cert: 'Chứng chỉ',
        nav_customer: 'Khách hàng',
        nav_partner: 'Đối tác',

        // Hero
        hero_badge: '🔒 Nền tảng An ninh mạng hàng đầu',
        hero_title_1: 'Bảo vệ tương lai',
        hero_title_2: 'số của bạn',
        hero_desc: 'Chúng tôi chuyên phát triển các giải pháp công nghệ từ AI, Blockchain đến Web Application. Bảo mật toàn diện cho doanh nghiệp của bạn.',
        hero_cta: 'Bắt đầu ngay',
        hero_cta2: 'Xem dịch vụ',
        hero_stat1_num: '500+',
        hero_stat1_label: 'Dự án hoàn thành',
        hero_stat2_num: '99.9%',
        hero_stat2_label: 'Uptime bảo mật',
        hero_stat3_num: '50+',
        hero_stat3_label: 'Đối tác toàn cầu',

        // Solutions / Services
        solutions_title: 'Giải pháp của chúng tôi',
        solutions_desc: 'Bộ giải pháp công nghệ toàn diện',
        svc_web: 'Phát triển Web',
        svc_web_desc: 'Phát triển web hiện đại, responsive với công nghệ mới nhất.',
        svc_ai: 'AI / Dữ liệu',
        svc_ai_desc: 'Giải pháp AI và phân tích dữ liệu giúp doanh nghiệp vượt trội.',
        svc_security: 'An ninh mạng',
        svc_security_desc: 'Bảo mật thông tin, mã hóa dữ liệu hàng đầu.',
        svc_blockchain: 'Blockchain',
        svc_blockchain_desc: 'Tư vấn và phát triển ứng dụng Blockchain chuyên nghiệp.',
        svc_cloud: 'Cloud Solutions',
        svc_cloud_desc: 'Hạ tầng đám mây tối ưu chi phí và hiệu năng.',
        svc_consulting: 'Tư vấn',
        svc_consulting_desc: 'Tư vấn chiến lược chuyển đổi số toàn diện.',
        learn_more: 'Tìm hiểu thêm',

        // How it works
        how_title: 'Quy trình làm việc',
        how_desc: 'Chúng tôi theo phương pháp agile, đảm bảo chất lượng tối ưu',
        how_step1_title: 'Phân tích & Tư vấn',
        how_step1_desc: 'Lắng nghe và hiểu nhu cầu, đánh giá rủi ro, lên kế hoạch chi tiết.',
        how_step2_title: 'Thiết kế & Phát triển',
        how_step2_desc: 'Xây dựng kiến trúc, phát triển giải pháp với công nghệ tiên tiến.',
        how_step3_title: 'Kiểm thử & Triển khai',
        how_step3_desc: 'Kiểm thử nghiêm ngặt, triển khai và giám sát liên tục 24/7.',
        how_step4_title: 'Hỗ trợ & Tối ưu',
        how_step4_desc: 'Hỗ trợ kỹ thuật, cập nhật bảo mật và tối ưu hiệu năng.',

        // Stats
        stats_title: 'Con số ấn tượng',
        stats_desc: 'Những thành tựu chúng tôi đã đạt được',
        stats_1_num: '10+',
        stats_1_label: 'Năm kinh nghiệm',
        stats_2_num: '500+',
        stats_2_label: 'Dự án hoàn thành',
        stats_3_num: '200+',
        stats_3_label: 'Khách hàng tin tưởng',
        stats_4_num: '50+',
        stats_4_label: 'Kỹ sư chuyên gia',

        // Testimonials
        testimonials_title: 'Khách hàng nói gì',
        testimonials_desc: 'Đánh giá từ những khách hàng đã sử dụng dịch vụ',
        testimonial_1: '"Đội ngũ rất chuyên nghiệp, giải pháp bảo mật của họ giúp chúng tôi an tâm hoàn toàn."',
        testimonial_1_name: 'Nguyễn Văn An',
        testimonial_1_title: 'CTO, TechCorp Việt Nam',
        testimonial_2: '"Ứng dụng web được phát triển vượt xa kỳ vọng, đội ngũ tận tâm và sáng tạo."',
        testimonial_2_name: 'Trần Minh Phương',
        testimonial_2_title: 'CEO, FinTech Solutions',
        testimonial_3: '"Giải pháp AI giúp chúng tôi tối ưu quy trình vận hành, tiết kiệm 40% chi phí."',
        testimonial_3_name: 'Lê Hoàng Duy',
        testimonial_3_title: 'COO, SmartFactory',

        // CTA
        cta_title: 'Sẵn sàng bảo vệ doanh nghiệp?',
        cta_desc: 'Liên hệ với đội ngũ chuyên gia của chúng tôi để nhận tư vấn miễn phí.',
        cta_btn: 'Liên hệ ngay',
        cta_btn2: 'Xem case studies',

        // Tech
        tech_title: 'Công nghệ sử dụng',
        tech_desc: 'Chúng tôi sử dụng những công nghệ mạnh mẽ và đáng tin cậy nhất',

        // Footer
        footer_desc: 'Nền tảng an ninh mạng và giải pháp công nghệ hàng đầu.',
        footer_company: 'Công ty',
        footer_about: 'Về chúng tôi',
        footer_careers: 'Tuyển dụng',
        footer_news: 'Tin tức',
        footer_contact: 'Liên hệ',
        footer_services: 'Dịch vụ',
        footer_security: 'An ninh mạng',
        footer_webdev: 'Phát triển Web',
        footer_ai: 'AI & Dữ liệu',
        footer_cloud: 'Cloud Solutions',
        footer_resources: 'Tài nguyên',
        footer_blog: 'Blog',
        footer_docs: 'Tài liệu',
        footer_support: 'Hỗ trợ',
        footer_lab: 'Lab demo',
        footer_rights: '© 2026 MyWeb. All rights reserved.',
        footer_privacy: 'Chính sách',
        footer_terms: 'Điều khoản',

        // Lab Hub
        lab_badge: 'Phòng thí nghiệm bảo mật',
        lab_hub_title_1: 'Cybersecurity',
        lab_hub_title_2: 'Interactive Lab',
        lab_hub_desc: 'Khám phá và thực hành các mô hình bảo mật thông qua mô phỏng tương tác. Học bằng cách làm — an toàn 100%, không rủi ro.',
        lab_stat_modules: 'Modules',
        lab_stat_interactive: 'Tương tác',
        lab_stat_risk: 'Rủi ro',
        lab_theory: 'Lý thuyết',
        lab_hide_theory: 'Ẩn lý thuyết',
        lab_show_theory: 'Hiện lý thuyết',
        lab_coming_soon: 'Module này đang được xây dựng. Vui lòng quay lại sau!',
        lab_under_construction: 'Đang phát triển',
        lab_diff_beginner: 'Cơ bản',
        lab_diff_intermediate: 'Trung bình',
        lab_diff_advanced: 'Nâng cao',

        // Lab Module Titles & Descriptions
        lab_encryption_title: 'Mã hóa & Giải mã',
        lab_encryption_desc: 'Tìm hiểu Caesar, AES, RSA — mã hóa đối xứng và bất đối xứng với demo trực quan từng bước.',
        lab_hashing_title: 'Hàm băm (Hashing)',
        lab_hashing_desc: 'So sánh MD5, SHA-256, Bcrypt. Khám phá hiệu ứng tuyết lở và tại sao hash không thể giải mã ngược.',
        lab_firewall_title: 'Tường lửa',
        lab_firewall_desc: 'Xây dựng quy tắc firewall, xem packet bị chặn hoặc cho phép qua hệ thống lọc mô phỏng.',
        lab_xss_title: 'XSS Attack',
        lab_xss_desc: 'Demo Cross-Site Scripting trong môi trường sandbox an toàn. So sánh vulnerable vs protected.',
        lab_sqli_title: 'SQL Injection',
        lab_sqli_desc: 'Thử inject SQL qua form đăng nhập giả lập. Hiểu cách prepared statements ngăn chặn tấn công.',
        lab_password_title: 'Bảo mật mật khẩu',
        lab_password_desc: 'Phân tích độ mạnh mật khẩu, mô phỏng brute force, tính entropy và thời gian crack.',
        lab_https_title: 'HTTPS & TLS',
        lab_https_desc: 'Xem animation TLS Handshake từng bước, hiểu certificate chain và demo tấn công Man-in-the-Middle.',
        lab_jwt_title: 'JWT Token',
        lab_jwt_desc: 'Tạo, giải mã và thử tamper JWT token. Hiểu header, payload, signature và các lỗ hổng phổ biến.',

        // Lab Progress & Gamification
        lab_progress_title: 'Tiến trình của bạn',
        lab_progress_completed: 'Đã hoàn thành',
        lab_progress_of: 'trên',
        lab_progress_modules: 'modules',
        lab_achievements_title: 'Thành tựu',
        lab_achievements_locked: 'Chưa mở khóa',
        lab_mark_complete: 'Đánh dấu hoàn thành',
        lab_completed_badge: 'Đã hoàn thành ✓',
        lab_reset_progress: 'Đặt lại',
        lab_reset_all: 'Đặt lại tất cả',
        lab_achievement_unlocked: 'Thành tựu mở khóa!',
        lab_filter_all: 'Tất cả',
        lab_filter_completed: 'Đã xong',
        lab_filter_incomplete: 'Chưa xong',
        ach_first_lab: 'Bước đầu tiên',
        ach_first_lab_desc: 'Hoàn thành lab đầu tiên',
        ach_three_labs: 'Tay nghề cao',
        ach_three_labs_desc: 'Hoàn thành 3 labs',
        ach_five_labs: 'Đang lên tay',
        ach_five_labs_desc: 'Hoàn thành 5 labs',
        ach_all_labs: 'Bậc thầy',
        ach_all_labs_desc: 'Hoàn thành tất cả labs',
        ach_crypto_master: 'Chuyên gia mã hóa',
        ach_crypto_master_desc: 'Hoàn thành Encryption + Hashing',
        ach_attack_expert: 'Tấn công chuyên nghiệp',
        ach_attack_expert_desc: 'Hoàn thành XSS + SQL Injection',
        ach_network_guru: 'Bậc thầy mạng',
        ach_network_guru_desc: 'Hoàn thành Firewall + HTTPS',
        ach_auth_specialist: 'Chuyên gia xác thực',
        ach_auth_specialist_desc: 'Hoàn thành JWT + Password',

        // Phase 3 — Pro
        lab_search_placeholder: 'Tìm kiếm lab...',
        lab_no_results: 'Không tìm thấy kết quả cho',
        lab_none_completed: 'Chưa lab nào hoàn thành. Hãy bắt đầu thôi!',
        lab_all_completed: 'Tuyệt vời! Đã hoàn thành tất cả!',
        cert_title: 'CHỨNG CHỈ HOÀN THÀNH',
        cert_subtitle: 'Chứng nhận đã hoàn thành thành công',
        cert_view: 'Xem chứng chỉ',
        cert_download: 'Tải chứng chỉ (SVG)',
        kb_title: 'Phím tắt',
        kb_prev: 'Lab trước',
        kb_next: 'Lab tiếp theo',
        kb_toggle_theory: 'Ẩn/Hiện lý thuyết',
        kb_home: 'Về trang Lab',
        kb_complete: 'Đánh dấu hoàn thành',
        kb_shortcuts: 'Hiện phím tắt',
        kb_close: 'Đóng',

        // CTF Arena
        ctf_title: 'Đấu trường CTF',
        ctf_subtitle: 'Giải mã thử thách, tìm Flag ẩn và ghi điểm.',
        ctf_instruction_title: 'Hướng dẫn tham gia',
        ctf_instruction_desc: 'CTF (Capture The Flag) là cuộc thi an toàn thông tin nơi bạn phải tìm ra các đoạn mã bí mật được gọi là "Flag" (định dạng CTF{...}) được ẩn giấu trong hệ thống.',
        ctf_how_to_play: 'Cách chơi:',
        ctf_step_1: 'Chọn một thử thách (Challenge) chưa hoàn thành.',
        ctf_step_2: 'Đọc kỹ mô tả và gợi ý (Hint).',
        ctf_step_3: 'Sử dụng các công cụ (DevTools, Decoder...) để tìm Flag.',
        ctf_step_4: 'Nhập Flag tìm được vào ô bên dưới và nhấn Submit.',
        ctf_example: 'Ví dụ: Nếu đề bài là "Flag ở ngay đây", bạn nhập CTF{example_flag}.',
        ctf_hint_btn: 'Cần gợi ý?',
        ctf_hide_hint: 'Ẩn gợi ý',
        ctf_submit: 'Gửi Flag',
        ctf_solved: 'Đã giải quyết!',
        ctf_congrats: 'XIN CHÚC MỪNG!',
        ctf_category_web: 'Web Security',
        ctf_category_crypto: 'Cryptography',
        ctf_category_misc: 'Miscellaneous',
        ctf_score: 'Điểm số của bạn',

        // Security Scanner
        scan_title: 'Security Header Scanner',
        scan_subtitle: 'Phân tích các tiêu đề bảo mật HTTP ngay lập tức.',
        scan_instruction_title: 'Cách công cụ hoạt động',
        scan_instruction_desc: 'Công cụ này gửi yêu cầu HTTP đến URL mục tiêu và phân tích các headers phản hồi để đánh giá mức độ an toàn.',
        scan_theory_hsts: 'HSTS (HTTP Strict Transport Security): Buộc trình duyệt luôn sử dụng HTTPS, ngăn chặn tấn công hạ cấp giao thức.',
        scan_theory_csp: 'CSP (Content Security Policy): Kiểm soát các nguồn tài nguyên (script, style, img...) được phép tải, giúp ngăn chặn XSS.',
        scan_theory_xframe: 'X-Frame-Options: Ngăn chặn trang web bị nhúng vào thẻ iframe của trang khác, chống tấn công Clickjacking.',
        scan_theory_nosniff: 'X-Content-Type-Options: Ngăn trình duyệt tự ý đoán (sniff) loại MIME của file, giảm nguy cơ thực thi file độc hại.',
        scan_btn: 'Quét ngay',
        scan_scanning: 'Đang quét...',
        scan_placeholder: 'Nhập URL (ví dụ: https://example.com)',
        scan_result_score: 'Điểm bảo mật',
        scan_target: 'Mục tiêu',
        scan_status: 'Trạng thái',
        scan_time: 'Thời gian',
        scan_details: 'Chi tiết phân tích',
        scan_note: '* Lưu ý: Do chính sách CORS của trình duyệt, công cụ này chỉ quét được chính trang web này hoặc các trang cho phép Cross-Origin request.',

        // About Page
        about_established: 'Thành lập 2026',
        about_we_are: 'Chúng tôi là',
        about_subtitle: 'Kết nối khoảng cách giữa ý tưởng và hiện thực. Chúng tôi là đối tác công nghệ hàng đầu, chuyên kiến tạo những trải nghiệm kỹ thuật số vượt trội, mang lại giá trị thực.',
        about_exp: 'Năm kinh nghiệm',
        about_projects: 'Dự án hoàn thành',
        about_experts: 'Chuyên gia công nghệ',
        about_satisfaction: 'Khách hàng hài lòng',
        about_quote: 'Chất lượng không phải là hành động, mà là thói quen.',
        about_pioneering: 'Tiên phong trong',
        about_digital_future: 'Tương lai số',
        about_founded_text: 'Được thành lập với tầm nhìn thay đổi cách doanh nghiệp tương tác với công nghệ, CyberShield đã phát triển từ một nhóm nhỏ đam mê lập trình thành một trung tâm đổi mới kỹ thuật số quy mô đầy đủ.',
        about_code_text: 'Chúng tôi không chỉ viết mã, chúng tôi kiến thiết giải pháp. Bằng cách tận dụng công nghệ AI, Blockchain và Web mới nhất, chúng tôi giúp các tổ chức mở rộng quy mô hiệu quả và an toàn trong bối cảnh kỹ thuật số không ngừng phát triển.',
        about_mission_title: 'Sứ mệnh',
        about_mission_desc: 'Mang đến các giải pháp công nghệ mạnh mẽ, có khả năng mở rộng và bảo mật, biến những thách thức phức tạp thành lợi thế cạnh tranh.',
        about_vision_title: 'Tầm nhìn',
        about_vision_desc: 'Trở thành chất xúc tác toàn cầu cho chuyển đổi số, thiết lập tiêu chuẩn cho sự đổi mới và độ tin cậy.',
        about_values_title: 'Giá trị cốt lõi',
        about_values_subtitle: 'Những nguyên tắc dẫn lối cho từng dòng code chúng tôi viết và từng mối quan hệ đối tác chúng tôi xây dựng.',
        about_val_innovation: 'Đổi mới là ưu tiên',
        about_val_innovation_desc: 'Chúng tôi không ngừng phá vỡ giới hạn, khám phá công nghệ mới để tìm ra giải pháp tốt hơn cho tương lai.',
        about_val_security: 'Bảo mật tuyệt đối',
        about_val_security_desc: 'Bảo mật không phải là suy nghĩ sau cùng. Nó được dệt vào cấu trúc của mọi thứ chúng tôi xây dựng, bảo vệ bạn và người dùng của bạn.',
        about_val_client: 'Khách hàng là trọng tâm',
        about_val_client_desc: 'Thành công của bạn là thành công của chúng tôi. Chúng tôi tuân thủ quy trình giao tiếp minh bạch và phát triển hợp tác.',
        about_team_title: 'Gặp gỡ chuyên gia',
        about_team_subtitle: 'Một đội ngũ đa dạng gồm những người có tầm nhìn, kỹ sư và nhà sáng tạo, gắn kết bởi niềm đam mê công nghệ.',
        about_role_ceo: 'CEO & Sáng lập',
        about_role_cto: 'Giám đốc công nghệ (CTO)',
        about_role_architect: 'Kiến trúc sư trưởng',
        about_role_design: 'Trưởng nhóm thiết kế',
        about_cta_ready: 'Sẵn sàng chuyển đổi doanh nghiệp?',
        about_cta_text: 'Hãy cùng thảo luận cách chúng tôi có thể giúp bạn xây dựng tương lai được hàng triệu người sử dụng.',
        about_cta_btn: 'Bắt đầu ngay',

        // About - Subsections
        about_partners_title: 'Đối tác',
        about_partners_subtitle: 'Xây dựng hệ sinh thái vững mạnh',
        about_certificates_title: 'Chứng chỉ',
        about_cert_qms: 'Hệ thống quản lý chất lượng',
        about_cert_issued: 'Cấp: Tháng 1 2026',
        about_customers_title: 'Khách hàng',
        about_customers_subtitle: 'Được tin tưởng bởi các doanh nghiệp toàn cầu',

        // Contact Page
        contact_title: 'Liên hệ',
        contact_title_highlight: 'CyberShield',
        contact_subtitle: 'Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn. Hãy cho chúng tôi biết làm thế nào chúng tôi có thể giúp doanh nghiệp của bạn phát triển.',
        contact_email_title: 'Email cho chúng tôi',
        contact_email_desc: 'Gửi yêu cầu hoặc câu hỏi chung',
        contact_phone_title: 'Gọi chúng tôi',
        contact_phone_desc: 'Thứ Hai - Thứ Sáu, 8am đến 6pm',
        contact_office_title: 'Ghé thăm văn phòng',
        contact_office_desc: 'Hãy đến uống cà phê và trò chuyện',
        contact_hours: 'Mở cửa: 8am - 6pm',
        contact_form_title: 'Gửi tin nhắn',
        contact_form_subtitle: 'Điền vào biểu mẫu bên dưới và chúng tôi sẽ liên hệ lại với bạn sớm nhất có thể.',
        contact_label_name: 'Họ tên',
        contact_placeholder_name: 'Nhập họ tên của bạn',
        contact_label_email: 'Địa chỉ Email',
        contact_placeholder_email: 'Nhập email của bạn',
        contact_label_subject: 'Chủ đề',
        contact_select_subject: 'Chọn chủ đề',
        contact_subject_general: 'Câu hỏi chung',
        contact_subject_support: 'Hỗ trợ kỹ thuật',
        contact_subject_sales: 'Tư vấn bán hàng',
        contact_subject_partnership: 'Hợp tác đối tác',
        contact_label_message: 'Tin nhắn',
        contact_placeholder_message: 'Bạn muốn chúng tôi giúp gì?',
        contact_submit: 'Gửi tin nhắn',
        contact_sending: 'Đang gửi...',
        contact_success_title: 'Tin nhắn đã gửi!',
        contact_success_message: 'Cảm ơn bạn đã liên hệ. Đội ngũ của chúng tôi sẽ phản hồi trong vòng 24 giờ.',
        contact_send_another: 'Gửi tin nhắn khác',
        contact_faq_title: 'Câu hỏi thường gặp',
        contact_faq_1_q: 'Thời gian phản hồi bao lâu?',
        contact_faq_1_a: 'Chúng tôi thường phản hồi trong vòng 24 giờ làm việc.',
        contact_faq_2_q: 'Bạn có hỗ trợ 24/7 không?',
        contact_faq_2_a: 'Gói doanh nghiệp bao gồm hỗ trợ khẩn cấp 24/7.',
        contact_faq_3_q: 'Văn phòng ở đâu?',
        contact_faq_3_a: 'Trụ sở chính tại TP.HCM, Việt Nam.',
        contact_support_hours: 'Giờ hỗ trợ',

        // Admin Dashboard
        admin_panel: 'Bảng quản trị',
        admin_overview: 'Tổng quan hệ thống',
        admin_db: 'Cơ sở dữ liệu',
        admin_users: 'Quản lý người dùng',
        admin_solutions: 'Quản lý Giải pháp',
        admin_settings: 'Cài đặt',
        admin_home: 'Về trang chủ',
        admin_logout: 'Đăng xuất',
        admin_stats_users: 'Tổng người dùng',
        admin_stats_msgs: 'Tin nhắn liên hệ',
        admin_stats_security: 'Cảnh báo bảo mật',
        admin_stats_status: 'Trạng thái hệ thống',
        admin_analytics: 'Thống kê dữ liệu',
        admin_chart_contacts: 'Liên hệ khách hàng',
        admin_chart_blogs: 'Bài viết & Tin tức',
        admin_chart_security: 'Trạng thái bảo mật',
        admin_recent_logs: 'Nhật ký bảo mật gần đây',
        admin_db_overview: 'Tổng quan cơ sở dữ liệu',
        admin_refresh: 'Làm mới',
        admin_loading: 'Đang tải...',

        // Auth Page
        auth_login: 'ĐĂNG NHẬP',
        auth_register: 'ĐĂNG KÝ',
        auth_mfa_title: 'XÁC THỰC MFA',
        auth_email_placeholder: 'Địa chỉ Email',
        auth_password_placeholder: 'Mật khẩu',
        auth_username_placeholder: 'Tên người dùng',
        auth_forgot_password: 'Quên mật khẩu?',
        auth_or_login_with: 'Hoặc đăng nhập bằng',
        auth_or_register_with: 'Hoặc đăng ký bằng',
        auth_welcome_back: 'Chào mừng trở lại!',
        auth_have_account: 'Đã có tài khoản?',
        auth_hello: 'Xin chào!',
        auth_no_account: 'Chưa có tài khoản?',
        auth_mobile_login: 'Đã có tài khoản? Đăng nhập',
        auth_mobile_register: 'Chưa có tài khoản? Đăng ký',
        auth_back_home: 'Về trang chủ',
        auth_mfa_code: 'Mã xác thực (6 số)',
        auth_confirm: 'XÁC NHẬN',
        auth_password_max: 'Mật khẩu tối đa 6 ký tự',
        auth_password_range: 'Mật khẩu phải tối thiểu 8 ký tự',
        auth_invalid_email: 'Email không hợp lệ.',
        auth_login_failed: 'Đăng nhập thất bại. Kiểm tra lại thông tin.',
        auth_register_failed: 'Đăng ký thất bại.',
        // Forgot Password
        auth_forgot_title: 'QUÊN MẬT KHẨU',
        auth_forgot_subtitle: 'Nhập email của bạn để khôi phục mật khẩu',
        auth_confirm_email: 'XÁC NHẬN EMAIL',
        auth_processing: 'Đang xử lý...',
        auth_back_login: 'Quay lại đăng nhập',
        auth_verify_title: 'XÁC THỰC TÀI KHOẢN',
        auth_verify_subtitle_provider: 'Tài khoản đăng nhập bằng',
        auth_verify_subtitle_code: 'Nhập mã xác thực đã gửi về email',
        auth_code_hint: 'Mã xác thực (demo)',
        auth_enter_code: 'Nhập mã 6 chữ số',
        auth_confirm_code: 'XÁC NHẬN MÃ',
        auth_code_error: 'Vui lòng nhập mã xác thực 6 chữ số',
        // Reset Password
        auth_reset_title: 'ĐẶT MẬT KHẨU MỚI',
        auth_reset_subtitle: 'Mật khẩu cũ sẽ bị xóa và thay bằng mật khẩu mới',
        auth_new_password: 'Mật khẩu mới',
        auth_confirm_password: 'Xác nhận mật khẩu mới',
        auth_password_rule_max: 'Tối đa 6 ký tự',
        auth_password_rule_range: 'Tối thiểu 8 ký tự',
        auth_password_rule_match: 'Mật khẩu khớp nhau',
        auth_confirm_mismatch: 'Mật khẩu xác nhận không khớp',
        auth_reset_btn: 'ĐẶT LẠI MẬT KHẨU',
        auth_error_generic: 'Có lỗi xảy ra',
        auth_terms_agree: 'Tôi đồng ý với',
        auth_terms_of_service: 'Điều khoản dịch vụ',
        auth_and: 'và',
        auth_privacy_policy: 'Chính sách bảo mật',
        auth_error_email_format: 'Email không đúng định dạng',
        auth_error_password_length: 'Mật khẩu phải từ 8 ký tự trở lên',
        auth_error_terms_required: 'Bạn cần đồng ý với các điều khoản dịch vụ và chính sách bảo mật.',

        // MFA Modal
        mfa_setup_title: 'THIẾT LẬP BẢO MẬT 2 LỚP (2FA)',
        mfa_setup_desc: 'Quét mã QR dưới đây bằng ứng dụng Authenticator (Google Authenticator, Authy...)',
        mfa_verify_title: 'XÁC THỰC BẢO MẬT',
        mfa_verify_desc: 'Nhập mã 6 chữ số từ ứng dụng Authenticator của bạn',
        mfa_cancel: 'Hủy / Về Đăng nhập',
        mfa_error_invalid: 'Mã xác thực không hợp lệ',
    },
    en: {
        // Navbar
        nav_products: 'PRODUCTS & SOLUTIONS',
        nav_about: 'ABOUT US',
        nav_contact: 'CONTACT',
        nav_lab: 'LAB & TOOLS',
        nav_ctf: 'CTF Arena',
        nav_scanner: 'Security Scanner',
        nav_news: 'BLOG & NEWS',
        nav_recruitment: 'RECRUITMENT',
        nav_login: 'Login',
        nav_dashboard: 'Dashboard',
        nav_logout: 'Logout',
        nav_intro: 'Introduction',
        nav_cert: 'Certificate',
        nav_customer: 'Customers',
        nav_partner: 'Partners',

        // Hero
        hero_badge: '🔒 Leading Cybersecurity Platform',
        hero_title_1: 'Protect your',
        hero_title_2: 'digital future',
        hero_desc: 'We specialize in AI, Blockchain, and Web Application solutions. Comprehensive security for your enterprise.',
        hero_cta: 'Get started',
        hero_cta2: 'View services',
        hero_stat1_num: '500+',
        hero_stat1_label: 'Projects completed',
        hero_stat2_num: '99.9%',
        hero_stat2_label: 'Security uptime',
        hero_stat3_num: '50+',
        hero_stat3_label: 'Global partners',

        // Solutions
        solutions_title: 'Our Solutions',
        solutions_desc: 'Comprehensive technology suite',
        svc_web: 'Web Development',
        svc_web_desc: 'Modern, responsive web development with the latest technologies.',
        svc_ai: 'AI / Data',
        svc_ai_desc: 'AI and data analytics solutions for business excellence.',
        svc_security: 'Cyber Security',
        svc_security_desc: 'Top-tier information security and data encryption.',
        svc_blockchain: 'Blockchain',
        svc_blockchain_desc: 'Professional blockchain application consulting and development.',
        svc_cloud: 'Cloud Solutions',
        svc_cloud_desc: 'Cost-optimized, high-performance cloud infrastructure.',
        svc_consulting: 'Consulting',
        svc_consulting_desc: 'Comprehensive digital transformation consulting strategy.',
        learn_more: 'Learn more',

        // How it works
        how_title: 'How We Work',
        how_desc: 'We follow agile methodology ensuring optimum quality',
        how_step1_title: 'Analysis & Consulting',
        how_step1_desc: 'Listen and understand needs, assess risks, create detailed plans.',
        how_step2_title: 'Design & Development',
        how_step2_desc: 'Build architecture, develop solutions with cutting-edge technology.',
        how_step3_title: 'Testing & Deployment',
        how_step3_desc: 'Rigorous testing, deployment, and 24/7 continuous monitoring.',
        how_step4_title: 'Support & Optimization',
        how_step4_desc: 'Technical support, security updates, and performance optimization.',

        // Stats
        stats_title: 'Impressive Numbers',
        stats_desc: 'Achievements we have accomplished',
        stats_1_num: '10+',
        stats_1_label: 'Years experience',
        stats_2_num: '500+',
        stats_2_label: 'Projects completed',
        stats_3_num: '200+',
        stats_3_label: 'Trusted clients',
        stats_4_num: '50+',
        stats_4_label: 'Expert engineers',

        // Testimonials
        testimonials_title: 'Client Testimonials',
        testimonials_desc: 'Reviews from clients who have used our services',
        testimonial_1: '"An extremely professional team. Their security solutions give us complete peace of mind."',
        testimonial_1_name: 'Nguyen Van An',
        testimonial_1_title: 'CTO, TechCorp Vietnam',
        testimonial_2: '"Web application exceeded all expectations. Dedicated and creative team."',
        testimonial_2_name: 'Tran Minh Phuong',
        testimonial_2_title: 'CEO, FinTech Solutions',
        testimonial_3: '"AI solutions helped us optimize operations, saving 40% in costs."',
        testimonial_3_name: 'Le Hoang Duy',
        testimonial_3_title: 'COO, SmartFactory',

        // CTA
        cta_title: 'Ready to protect your business?',
        cta_desc: 'Contact our expert team for a free consultation.',
        cta_btn: 'Contact us',
        cta_btn2: 'View case studies',

        // Tech
        tech_title: 'Technologies We Use',
        tech_desc: 'We use the most powerful and reliable technologies',

        // Footer
        footer_desc: 'Leading cybersecurity and technology solutions platform.',
        footer_company: 'Company',
        footer_about: 'About us',
        footer_careers: 'Careers',
        footer_news: 'News',
        footer_contact: 'Contact',
        footer_services: 'Services',
        footer_security: 'Cyber Security',
        footer_webdev: 'Web Development',
        footer_ai: 'AI & Data',
        footer_cloud: 'Cloud Solutions',
        footer_resources: 'Resources',
        footer_blog: 'Blog',
        footer_docs: 'Documentation',
        footer_support: 'Support',
        footer_lab: 'Lab demo',
        footer_rights: '© 2026 MyWeb. All rights reserved.',
        footer_privacy: 'Privacy',
        footer_terms: 'Terms',

        // Lab Hub
        lab_badge: 'Security Laboratory',
        lab_hub_title_1: 'Cybersecurity',
        lab_hub_title_2: 'Interactive Lab',
        lab_hub_desc: 'Explore and practice security models through interactive simulations. Learn by doing — 100% safe, zero risk.',
        lab_stat_modules: 'Modules',
        lab_stat_interactive: 'Interactive',
        lab_stat_risk: 'Risk',
        lab_theory: 'Theory',
        lab_hide_theory: 'Hide theory',
        lab_show_theory: 'Show theory',
        lab_coming_soon: 'This module is under construction. Please check back later!',
        lab_under_construction: 'Under construction',
        lab_diff_beginner: 'Beginner',
        lab_diff_intermediate: 'Intermediate',
        lab_diff_advanced: 'Advanced',

        // Lab Module Titles & Descriptions
        lab_encryption_title: 'Encryption & Decryption',
        lab_encryption_desc: 'Explore Caesar, AES, RSA — symmetric and asymmetric encryption with step-by-step visual demos.',
        lab_hashing_title: 'Hashing Functions',
        lab_hashing_desc: 'Compare MD5, SHA-256, Bcrypt. Discover the avalanche effect and why hashes are one-way.',
        lab_firewall_title: 'Firewall Simulator',
        lab_firewall_desc: 'Build firewall rules, watch packets get blocked or allowed through the simulated filtering system.',
        lab_xss_title: 'XSS Attack',
        lab_xss_desc: 'Demo Cross-Site Scripting in a safe sandbox environment. Compare vulnerable vs protected modes.',
        lab_sqli_title: 'SQL Injection',
        lab_sqli_desc: 'Try injecting SQL through a simulated login form. Understand how prepared statements prevent attacks.',
        lab_password_title: 'Password Security',
        lab_password_desc: 'Analyze password strength, simulate brute force attacks, calculate entropy and crack time.',
        lab_https_title: 'HTTPS & TLS',
        lab_https_desc: 'Watch TLS Handshake animation step-by-step, understand certificate chains and MITM attack demo.',
        lab_jwt_title: 'JWT Token',
        lab_jwt_desc: 'Create, decode and tamper JWT tokens. Understand header, payload, signature and common vulnerabilities.',

        // Lab Progress & Gamification
        lab_progress_title: 'Your Progress',
        lab_progress_completed: 'Completed',
        lab_progress_of: 'of',
        lab_progress_modules: 'modules',
        lab_achievements_title: 'Achievements',
        lab_achievements_locked: 'Locked',
        lab_mark_complete: 'Mark as Complete',
        lab_completed_badge: 'Completed ✓',
        lab_reset_progress: 'Reset',
        lab_reset_all: 'Reset All',
        lab_achievement_unlocked: 'Achievement Unlocked!',
        lab_filter_all: 'All',
        lab_filter_completed: 'Completed',
        lab_filter_incomplete: 'In Progress',
        ach_first_lab: 'First Steps',
        ach_first_lab_desc: 'Complete your first lab',
        ach_three_labs: 'Getting Skilled',
        ach_three_labs_desc: 'Complete 3 labs',
        ach_five_labs: 'On Fire',
        ach_five_labs_desc: 'Complete 5 labs',
        ach_all_labs: 'Grand Master',
        ach_all_labs_desc: 'Complete all labs',
        ach_crypto_master: 'Crypto Master',
        ach_crypto_master_desc: 'Complete Encryption + Hashing',
        ach_attack_expert: 'Attack Expert',
        ach_attack_expert_desc: 'Complete XSS + SQL Injection',
        ach_network_guru: 'Network Guru',
        ach_network_guru_desc: 'Complete Firewall + HTTPS',
        ach_auth_specialist: 'Auth Specialist',
        ach_auth_specialist_desc: 'Complete JWT + Password',

        // Phase 3 — Pro
        lab_search_placeholder: 'Search labs...',
        lab_no_results: 'No results found for',
        lab_none_completed: 'No labs completed yet. Let\'s get started!',
        lab_all_completed: 'Awesome! All labs completed!',
        cert_title: 'CERTIFICATE OF COMPLETION',
        cert_subtitle: 'This certifies successful completion of',
        cert_view: 'View Certificate',
        cert_download: 'Download Certificate (SVG)',
        kb_title: 'Keyboard Shortcuts',
        kb_prev: 'Previous Lab',
        kb_next: 'Next Lab',
        kb_toggle_theory: 'Toggle Theory Panel',
        kb_home: 'Go to Lab Hub',
        kb_complete: 'Mark as Complete',
        kb_shortcuts: 'Show Shortcuts',
        kb_close: 'Close',

        // CTF Arena
        ctf_title: 'CTF Arena',
        ctf_subtitle: 'Solve challenges, find hidden Flags, and earn points.',
        ctf_instruction_title: 'How to Play',
        ctf_instruction_desc: 'CTF (Capture The Flag) is a cybersecurity competition where you must find secret strings called "Flags" (format CTF{...}) hidden within the system.',
        ctf_how_to_play: 'Steps:',
        ctf_step_1: 'Select an unsolved Challenge.',
        ctf_step_2: 'Read the description and Hint carefully.',
        ctf_step_3: 'Use tools (DevTools, Decoder...) to find the Flag.',
        ctf_step_4: 'Enter the found Flag below and click Submit.',
        ctf_example: 'Example: If the task is "Flag is here", enter CTF{example_flag}.',
        ctf_hint_btn: 'Need a Hint?',
        ctf_hide_hint: 'Hide Hint',
        ctf_submit: 'Submit Flag',
        ctf_solved: 'Solved!',
        ctf_congrats: 'CONGRATULATIONS!',
        ctf_category_web: 'Web Security',
        ctf_category_crypto: 'Cryptography',
        ctf_category_misc: 'Miscellaneous',
        ctf_score: 'Your Score',

        // Security Scanner
        scan_title: 'Security Header Scanner',
        scan_subtitle: 'Analyze HTTP security headers instantly.',
        scan_instruction_title: 'How it Works',
        scan_instruction_desc: 'This tool sends an HTTP request to the target URL and analyzes the response headers to evaluate security posture.',
        scan_theory_hsts: 'HSTS (HTTP Strict Transport Security): Forces browsers to use HTTPS, preventing protocol downgrade attacks.',
        scan_theory_csp: 'CSP (Content Security Policy): Controls resources (scripts, images) the user agent is allowed to load, preventing XSS.',
        scan_theory_xframe: 'X-Frame-Options: Prevents the site from being embedded in iframes, stopping Clickjacking attacks.',
        scan_theory_nosniff: 'X-Content-Type-Options: Prevents browsers from sniffing MIME types, reducing risk of malicious file execution.',
        scan_btn: 'Scan Now',
        scan_scanning: 'Scanning...',
        scan_placeholder: 'Enter URL (e.g. https://example.com)',
        scan_result_score: 'Security Score',
        scan_target: 'Target',
        scan_status: 'Status',
        scan_time: 'Time',
        scan_details: 'Analysis Details',
        scan_note: '* Note: Due to browser CORS policy, this client-side tool can only scan this origin or CORS-enabled targets.',

        // About Page
        about_established: 'Established 2026',
        about_we_are: 'We Are',
        about_subtitle: 'Bridging the gap between imagination and implementation. We are a premier technology partner dedicated to crafting exceptional digital experiences that drive real value.',
        about_exp: 'Years Experience',
        about_projects: 'Projects Delivered',
        about_experts: 'Tech Experts',
        about_satisfaction: 'Client Satisfaction',
        about_quote: 'Quality is not an act, it is a habit.',
        about_pioneering: 'Pioneering the',
        about_digital_future: 'Digital Future',
        about_founded_text: 'Founded with a vision to transform how businesses interact with technology, CyberShield has grown from a small collective of passionate developers into a full-scale digital innovation house.',
        about_code_text: 'We don\'t just write code; we architect solutions. By leveraging the latest in AI, Blockchain, and Web technologies, we empower organizations to scale efficiently and securely in an ever-evolving digital landscape.',
        about_mission_title: 'Our Mission',
        about_mission_desc: 'To deliver robust, scalable, and secure technology solutions that turn complex challenges into competitive advantages.',
        about_vision_title: 'Our Vision',
        about_vision_desc: 'To be the global catalyst for digital transformation, setting the standard for innovation and reliability.',
        about_values_title: 'Our Core Values',
        about_values_subtitle: 'The principles that guide every line of code we write and every partnership we build.',
        about_val_innovation: 'Innovation First',
        about_val_innovation_desc: 'We constantly push boundaries, exploring new technologies to find better solutions for tomorrow\'s problems.',
        about_val_security: 'Uncompromised Security',
        about_val_security_desc: 'Security isn\'t an afterthought. It\'s woven into the fabric of everything we build, protecting you and your users.',
        about_val_client: 'Client-Centric',
        about_val_client_desc: 'Your success is our success. We adhere to transparent communication and collaborative development processes.',
        about_team_title: 'Meet The Experts',
        about_team_subtitle: 'A diverse team of visionaries, engineers, and creators united by a passion for technology.',
        about_role_ceo: 'CEO & Founder',
        about_role_cto: 'CTO',
        about_role_architect: 'Lead Architect',
        about_role_design: 'Head of Design',
        about_cta_ready: 'Ready to Transform Your Business?',
        about_cta_text: 'Let\'s discuss how we can help you build the future used by millions.',
        about_cta_btn: 'Get Started Now',

        // About - Subsections
        about_partners_title: 'Our Partners',
        about_partners_subtitle: 'Building a strong ecosystem',
        about_certificates_title: 'Certificates',
        about_cert_qms: 'Quality Management System',
        about_cert_issued: 'Issued: Jan 2026',
        about_customers_title: 'Our Customers',
        about_customers_subtitle: 'Trusted by global enterprises',

        // Contact Page
        contact_title: 'Get in Touch with',
        contact_title_highlight: 'CyberShield',
        contact_subtitle: 'We are here to help and answer any question you might have. We look forward to hearing from you.',
        contact_email_title: 'Email Us',
        contact_email_desc: 'Send us a general inquiry or question',
        contact_phone_title: 'Call Us',
        contact_phone_desc: 'Mon-Fri from 8am to 6pm',
        contact_office_title: 'Visit Our Office',
        contact_office_desc: 'Come say hello at our office HQ',
        contact_hours: 'Open: 8am - 6pm',
        contact_form_title: 'Send a Message',
        contact_form_subtitle: 'Fill out the form below and we will get back to you as soon as possible.',
        contact_label_name: 'Full Name',
        contact_placeholder_name: 'Enter your full name',
        contact_label_email: 'Email Address',
        contact_placeholder_email: 'Enter your email address',
        contact_label_subject: 'Subject',
        contact_select_subject: 'Select a subject',
        contact_subject_general: 'General Inquiry',
        contact_subject_support: 'Technical Support',
        contact_subject_sales: 'Sales Consultation',
        contact_subject_partnership: 'Partnership',
        contact_label_message: 'Message',
        contact_placeholder_message: 'How can we help you?',
        contact_submit: 'Send Message',
        contact_sending: 'Sending...',
        contact_success_title: 'Message Sent!',
        contact_success_message: 'Thanks for reaching out. Our team will respond within 24 hours.',
        contact_send_another: 'Send Another Message',
        contact_faq_title: 'Frequently Asked Questions',
        contact_faq_1_q: 'What is the response time?',
        contact_faq_1_a: 'We typically respond within 24 business hours.',
        contact_faq_2_q: 'Do you offer 24/7 support?',
        contact_faq_2_a: 'Enterprise plans include 24/7 emergency support.',
        contact_faq_3_q: 'Where are you located?',
        contact_faq_3_a: 'Our HQ is in Ho Chi Minh City, Vietnam.',
        contact_support_hours: 'Support Hours',

        // Admin Dashboard
        admin_panel: 'Admin Panel',
        admin_overview: 'System Overview',
        admin_db: 'Database Manager',
        admin_users: 'User Management',
        admin_solutions: 'Solutions Management',
        admin_settings: 'Settings',
        admin_home: 'Back to Home',
        admin_logout: 'Logout',
        admin_stats_users: 'Total Users',
        admin_stats_msgs: 'Contact Messages',
        admin_stats_security: 'Security Alerts',
        admin_stats_status: 'System Status',
        admin_analytics: 'Data Analytics',
        admin_chart_contacts: 'Client Contacts',
        admin_chart_blogs: 'Blogs & News',
        admin_chart_security: 'Security Status',
        admin_recent_logs: 'Recent Security Logs',
        admin_db_overview: 'Database Overview',
        admin_refresh: 'Refresh',
        admin_loading: 'Loading...',

        // Auth Page
        auth_login: 'SIGN IN',
        auth_register: 'SIGN UP',
        auth_mfa_title: 'MFA VERIFICATION',
        auth_email_placeholder: 'Email Address',
        auth_password_placeholder: 'Password',
        auth_username_placeholder: 'Username',
        auth_forgot_password: 'Forgot password?',
        auth_or_login_with: 'Or sign in with',
        auth_or_register_with: 'Or sign up with',
        auth_welcome_back: 'Welcome back!',
        auth_have_account: 'Already have an account?',
        auth_hello: 'Hello!',
        auth_no_account: "Don't have an account?",
        auth_mobile_login: 'Already have an account? Sign In',
        auth_mobile_register: "Don't have an account? Sign Up",
        auth_back_home: 'Back to home',
        auth_mfa_code: 'Verification code (6 digits)',
        auth_confirm: 'VERIFY',
        auth_password_max: 'Password must be at most 6 characters',
        auth_password_range: 'Password must be at least 8 characters',
        auth_invalid_email: 'Invalid email address.',
        auth_login_failed: 'Login failed. Please check your credentials.',
        auth_register_failed: 'Registration failed.',
        // Forgot Password
        auth_forgot_title: 'FORGOT PASSWORD',
        auth_forgot_subtitle: 'Enter your email to recover your password',
        auth_confirm_email: 'VERIFY EMAIL',
        auth_processing: 'Processing...',
        auth_back_login: 'Back to login',
        auth_verify_title: 'VERIFY ACCOUNT',
        auth_verify_subtitle_provider: 'Account linked with',
        auth_verify_subtitle_code: 'Enter the verification code sent to your email',
        auth_code_hint: 'Verification code (demo)',
        auth_enter_code: 'Enter 6-digit code',
        auth_confirm_code: 'VERIFY CODE',
        auth_code_error: 'Please enter a 6-digit verification code',
        // Reset Password
        auth_reset_title: 'SET NEW PASSWORD',
        auth_reset_subtitle: 'Your old password will be replaced with a new one',
        auth_new_password: 'New password',
        auth_confirm_password: 'Confirm new password',
        auth_password_rule_max: 'Maximum 6 characters',
        auth_password_rule_range: 'At least 8 characters',
        auth_password_rule_match: 'Passwords match',
        auth_confirm_mismatch: 'Passwords do not match',
        auth_reset_btn: 'RESET PASSWORD',
        auth_error_generic: 'An error occurred',
        auth_terms_agree: 'I agree to the',
        auth_terms_of_service: 'Terms of Service',
        auth_and: 'and',
        auth_privacy_policy: 'Privacy Policy',
        auth_error_email_format: 'Invalid email format',
        auth_error_password_length: 'Password must be at least 8 characters',
        auth_error_terms_required: 'You must agree to the Terms of Service and Privacy Policy.',
    }
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('vi')

    const t = (key) => translations[lang]?.[key] || key

    const toggleLang = () => setLang(prev => prev === 'vi' ? 'en' : 'vi')

    return (
        <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => useContext(LanguageContext)
